/****************************************************************************/
/* Project: Ax-Zynq Control Board                                           */
/*                                                                          */
/* Copyright © 2021, Ningbo Physis Technology Co.,Ltd. All Rights Reserved. */
/*                                                                          */
/* File        : MemoryLayout.c                                             */
/* Author      : Stefano Martino                                            */
/*               Fabio Terrile                                              */
/*               Hu Xiaokai                                                 */
/* Description :                                                            */
/*                                                                          */
/****************************************************************************/
// Compiler Option
#pragma GCC optimize (2)

#include "common\CommonDefines.h"
#include "common\SecurityCrypto.h"

#include "MemoryLayout.h"

#ifdef _AXX_SYSAPP
#include "fpga\FpgaHandler.h"
#include "common\CommonUtility.h"
#include "system\SystemAlarms.h"
#endif

#include "core\Flash.h"
#include "xparameters.h"

#define XPAR_PS7_L2CACHE_S_AXI_BASEADDR  (0xF9000000)
#define XPAR_PS7_L2CACHE_S_AXI_HIGHADDR  (0xF9000000+0x0007FFFF)

//***************************************************************************
// Memory layout for System Application

#ifdef _AXX_SYSAPP

static const MEMORY_SECTOR_INFO  sMemorySectorInfos[] =
{
#ifndef _INFINEON
  // ZYNQ-7000 Memory OCM DDR
#ifdef XPAR_PS7_RAM_0_S_AXI_BASEADDR
                        XPAR_PS7_RAM_0_S_AXI_BASEADDR, XPAR_PS7_RAM_0_S_AXI_HIGHADDR, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif
#ifdef XPAR_PS7_RAM_1_S_AXI_BASEADDR
                        XPAR_PS7_RAM_1_S_AXI_BASEADDR, XPAR_PS7_RAM_1_S_AXI_HIGHADDR, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif
#ifdef XPAR_PS7_DDR_0_S_AXI_BASEADDR
                        XPAR_PS7_DDR_0_S_AXI_BASEADDR, XPAR_PS7_DDR_0_S_AXI_HIGHADDR,   SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#else
                        XPAR_PS7_L2CACHE_S_AXI_BASEADDR, XPAR_PS7_L2CACHE_S_AXI_HIGHADDR, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif

  // FPGA Custom App, accessible for PLC Debug
  /*     512  bytes */  FPGA_REGISTER_BASE_ADDRESS+FPGA_CUSTOMAPP_BASEADDR, FPGA_REGISTER_BASE_ADDRESS+FPGA_CUSTOMAPP_BASEADDR+FPGA_CUSTOMAPP_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /*    4096  bytes */  FPGA_REGISTER_BASE_ADDRESS, FPGA_REGISTER_BASE_ADDRESS+FPGA_STANDARD_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ,
  /*   16384  bytes */  FPGA_ETHERNET_BASE_ADDRESS, FPGA_ETHERNET_BASE_ADDRESS+FPGA_ETHERNET_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE, // $TEST$
  
  // System Reset Parameters Areas
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C00000, XPS_QSPI_LINEAR_BASEADDR+0x00C0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,

  // SysLog Areas
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C10000, XPS_QSPI_LINEAR_BASEADDR+0x00C1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C20000, XPS_QSPI_LINEAR_BASEADDR+0x00C2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C30000, XPS_QSPI_LINEAR_BASEADDR+0x00C3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,

  // Parameters Areas
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C40000, XPS_QSPI_LINEAR_BASEADDR+0x00C4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C50000, XPS_QSPI_LINEAR_BASEADDR+0x00C5FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,

  // AlarmLog Areas
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C60000, XPS_QSPI_LINEAR_BASEADDR+0x00C6FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C70000, XPS_QSPI_LINEAR_BASEADDR+0x00C7FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,

  // Activation keys Area
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C80000, XPS_QSPI_LINEAR_BASEADDR+0x00C8FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ ,

  // Bootblock parameters Area
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00C90000, XPS_QSPI_LINEAR_BASEADDR+0x00C9FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ ,

  // PLC Code Area - ZYNQ
  /*     128 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00CD0000, XPS_QSPI_LINEAR_BASEADDR+0x00CEFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,

  // PLC requested memory area storage
  /*      64 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00CF0000, XPS_QSPI_LINEAR_BASEADDR+0x00CFFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // PLC source code storage
  /*     320 Kbytes */  XPS_QSPI_LINEAR_BASEADDR+0x00800000, XPS_QSPI_LINEAR_BASEADDR+0x0084FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
#else
  // XE167 Data SRAM, accessible for PLC Debug
#ifndef _APP_XC
  /*       8 Kbytes */  0x0000A000, 0x0000BFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#else
  /*       8 Kbytes */  0x00008000, 0x0000BFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif
  /*       8 Kbytes */  0x0000C000, 0x0000D5FF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /*     512  bytes */  0x0000FD00, 0x0000FEFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,

  // XE167 Program SRAM, accessible for PLC Debug
  /*      55 Kbytes */  0x00E05000, 0x00E0FBFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,

  // FPGA Custom App, accessible for PLC Debug
  /*     512  bytes */  FPGA_REGISTER_BASE_ADDRESS+FPGA_CUSTOMAPP_BASEADDR, FPGA_REGISTER_BASE_ADDRESS+FPGA_CUSTOMAPP_BASEADDR+FPGA_CUSTOMAPP_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /*    4096  bytes */  FPGA_REGISTER_BASE_ADDRESS, FPGA_REGISTER_BASE_ADDRESS+FPGA_STANDARD_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ,
  /*   16384  bytes */  FPGA_ETHERNET_BASE_ADDRESS, FPGA_ETHERNET_BASE_ADDRESS+FPGA_ETHERNET_SIZE-1, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE, // $TEST$

  // SysLog Areas
  /*       4 Kbytes */  0x00C01000, 0x00C01FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*       4 Kbytes */  0x00C02000, 0x00C02FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*       4 Kbytes */  0x00C03000, 0x00C03FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,

  // Parameters Areas
  /*      12 Kbytes */  0x00C05000, 0x00C07FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /*      12 Kbytes */  0x00C08000, 0x00C0AFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
 
  // AlarmLog Areas
  /*       4 Kbytes */  0x00C0B000, 0x00C0BFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,
  /*       4 Kbytes */  0x00C0C000, 0x00C0CFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ,

  // Activation keys Area
  /*       4 Kbytes */  0x00C0D000, 0x00C0DFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ ,

  // Bootblock parameters Area
  /*       4 Kbytes */  0x00C0E000, 0x00C0EFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ ,


  // CONST Flash Area
  /*    15.5 Kbytes */  0x00C50220, 0x00C53FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_READ ,

  // PLC Code Area
#ifndef _APP_XC
  // XE167F
  /*      64 Kbytes */  0x00C40000, 0x00C4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#else
  // XC2788X
  /*     128 Kbytes */  0x00CC0000, 0x00CDFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif // _app_xc

#ifdef _APP_XC
  // External Serial Data Flash, access only for Remote Display Application HMI
  /* S01: 64 Kbytes */  0x00810000, 0x0081FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S02: 64 Kbytes */  0x00820000, 0x0082FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S03: 64 Kbytes */  0x00830000, 0x0083FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S04: 64 Kbytes */  0x00840000, 0x0084FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S05: 64 Kbytes */  0x00850000, 0x0085FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // External Serial Data Flash, access only for AxX app storage
  /* S13: 64 Kbytes */  0x008D0000, 0x008DFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S14: 64 Kbytes */  0x008E0000, 0x008EFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S15: 64 Kbytes */  0x008F0000, 0x008FFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S16: 64 Kbytes */  0x00900000, 0x0090FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S17: 64 Kbytes */  0x00910000, 0x0091FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // External Serial Data Flash, system application storage
  /* S18: 64 KBytes */  0x00920000, 0x0092FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S19: 64 KBytes */  0x00930000, 0x0093FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S20: 64 KBytes */  0x00940000, 0x0094FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S21: 64 KBytes */  0x00950000, 0x0095FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S22: 64 KBytes */  0x00960000, 0x0096FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S23: 64 KBytes */  0x00970000, 0x0097FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S24: 64 KBytes */  0x00980000, 0x0098FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S25: 64 KBytes */  0x00990000, 0x0099FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S26: 64 KBytes */  0x009A0000, 0x009AFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S27: 64 KBytes */  0x009B0000, 0x009BFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S28: 64 KBytes */  0x009C0000, 0x009CFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S29: 64 KBytes */  0x009D0000, 0x009DFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S30: 64 KBytes */  0x009E0000, 0x009EFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S31: 64 KBytes */  0x009F0000, 0x009FFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S32: 64 KBytes */  0x00A00000, 0x00A0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S33: 64 KBytes */  0x00A10000, 0x00A1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S34: 64 KBytes */  0x00A20000, 0x00A2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S35: 64 KBytes */  0x00A30000, 0x00A3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S36: 64 KBytes */  0x00A40000, 0x00A4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S37: 64 KBytes */  0x00A50000, 0x00A5FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S38: 64 KBytes */  0x00A60000, 0x00A6FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S39: 64 KBytes */  0x00A70000, 0x00A7FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S40: 64 KBytes */  0x00A80000, 0x00A8FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S41: 64 KBytes */  0x00A90000, 0x00A9FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S42: 64 KBytes */  0x00AA0000, 0x00AAFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S43: 64 KBytes */  0x00AB0000, 0x00ABFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S44: 64 KBytes */  0x00AC0000, 0x00ACFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S45: 64 KBytes */  0x00AD0000, 0x00ADFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S46: 64 KBytes */  0x00AE0000, 0x00AEFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S47: 64 KBytes */  0x00AF0000, 0x00AFFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S48: 64 KBytes */  0x00B00000, 0x00B0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S49: 64 KBytes */  0x00B10000, 0x00B1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S50: 64 KBytes */  0x00B20000, 0x00B2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S51: 64 KBytes */  0x00B30000, 0x00B3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S52: 64 KBytes */  0x00B40000, 0x00B4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S53: 64 KBytes */  0x00B50000, 0x00B5FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S54: 64 KBytes */  0x00B60000, 0x00B6FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S55: 64 KBytes */  0x00B70000, 0x00B7FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S56: 64 KBytes */  0x00B80000, 0x00B8FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S57: 64 KBytes */  0x00B90000, 0x00B9FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S58: 64 KBytes */  0x00BA0000, 0x00BAFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S59: 64 KBytes */  0x00BB0000, 0x00BBFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S60: 64 KBytes */  0x00BC0000, 0x00BCFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S61: 64 KBytes */  0x00BD0000, 0x00BDFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S62: 64 KBytes */  0x00BE0000, 0x00BEFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S63: 64 KBytes */  0x00BF0000, 0x00BFFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
#else
 // External Serial Data Flash, access only for Remote Display System HMI
 /* S08: 64 Kbytes */  0x00880000, 0x0088FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S09: 64 Kbytes */  0x00890000, 0x0089FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S10: 64 Kbytes */  0x008A0000, 0x008AFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S11: 64 Kbytes */  0x008B0000, 0x008BFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S12: 64 Kbytes */  0x008C0000, 0x008CFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

 // External Serial Data Flash, access only for AxX app storage
 /* S13: 64 Kbytes */  0x008D0000, 0x008DFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S14: 64 Kbytes */  0x008E0000, 0x008EFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S15: 64 Kbytes */  0x008F0000, 0x008FFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

 // External Serial Data Flash, access only for Remote Display Application HMI
 /* S16: 64 Kbytes */  0x00900000, 0x0090FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S17: 64 Kbytes */  0x00910000, 0x0091FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S18: 64 Kbytes */  0x00920000, 0x0092FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S19: 64 Kbytes */  0x00930000, 0x0093FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
 /* S20: 64 Kbytes */  0x00940000, 0x0094FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
#endif // _app_xc
#endif // _infineon
};

#endif // _AXX_SYSAPP

/////////////////////////////////////////////////////////////////////////////
//

#ifdef _AXX_BOOTBLOCK 

static MEMORY_SECTOR_INFO sMemorySectorInfos[] =
{
#ifndef _INFINEON

  // ZYNQ-7000 Memory OCM DDR
#ifdef XPAR_PS7_RAM_0_S_AXI_BASEADDR
                        XPAR_PS7_RAM_0_S_AXI_BASEADDR,       XPAR_PS7_RAM_0_S_AXI_HIGHADDR,       SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif
#ifdef XPAR_PS7_RAM_1_S_AXI_BASEADDR
                        XPAR_PS7_RAM_1_S_AXI_BASEADDR,       XPAR_PS7_RAM_1_S_AXI_HIGHADDR,       SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif
#ifdef XPAR_PS7_DDR_0_S_AXI_BASEADDR
                        XPAR_PS7_DDR_0_S_AXI_BASEADDR,       XPAR_PS7_DDR_0_S_AXI_HIGHADDR,       SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#else
                        XPAR_PS7_L2CACHE_S_AXI_BASEADDR,     XPAR_PS7_L2CACHE_S_AXI_HIGHADDR,     SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
#endif

  // ZYNQ-7000 QSPI FLASH: Firmware
                        XPS_QSPI_LINEAR_BASEADDR+0x350000,   XPS_QSPI_LINEAR_BASEADDR+0xBFFFFF,   SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

#else
  // XE167 Data SRAM
  /*      16 Kbytes */  0x0000A000, 0x0000DFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,

  // XE167 Program SRAM
  /*      64 Kbytes */  0x00E00000, 0x00E0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_NORMAL | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
                                              
  // XE167 Internal Program Flash 0           
  /* S00:  4 Kbytes */  0x00C00000, 0x00C00FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH,
  /* S01:  4 Kbytes */  0x00C01000, 0x00C01FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S02:  4 Kbytes */  0x00C02000, 0x00C02FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S03:  4 Kbytes */  0x00C03000, 0x00C03FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S04: 16 Kbytes */  0x00C04000, 0x00C07FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S05: 16 Kbytes */  0x00C08000, 0x00C0BFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S06: 12 Kbytes */  0x00C0C000, 0x00C0EFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ ,
  /* S07: 64 Kbytes */  0x00C10000, 0x00C1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH,
  /* S08: 64 Kbytes */  0x00C20000, 0x00C2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S09: 64 Kbytes */  0x00C30000, 0x00C3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // XE167 Internal Program Flash 1
  /* S10:  4 Kbytes */  0x00C40000, 0x00C40FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S11:  4 Kbytes */  0x00C41000, 0x00C41FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S12:  4 Kbytes */  0x00C42000, 0x00C42FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S13:  4 Kbytes */  0x00C43000, 0x00C43FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S14: 16 Kbytes */  0x00C44000, 0x00C47FFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S15: 16 Kbytes */  0x00C48000, 0x00C4BFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S16: 16 Kbytes */  0x00C4C000, 0x00C4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_READ | MEMORY_CONFIG_WRITE,
  /* S17: 64 Kbytes */  0x00C50000, 0x00C5FFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S18: 64 Kbytes */  0x00C60000, 0x00C6FFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S19: 64 Kbytes */  0x00C70000, 0x00C7FFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // XE167 Internal Program Flash 2
  /* S20:  4 Kbytes */  0x00C80000, 0x00C80FFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S21:  4 Kbytes */  0x00C81000, 0x00C81FFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S22:  4 Kbytes */  0x00C82000, 0x00C82FFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S23:  4 Kbytes */  0x00C83000, 0x00C83FFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S24: 16 Kbytes */  0x00C84000, 0x00C87FFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S25: 16 Kbytes */  0x00C88000, 0x00C8BFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S26: 16 Kbytes */  0x00C8C000, 0x00C8FFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S27: 64 Kbytes */  0x00C90000, 0x00C9FFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S28: 64 Kbytes */  0x00CA0000, 0x00CAFFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S29: 64 Kbytes */  0x00CB0000, 0x00CBFFFF, SECURITY_CRYPTO_KEY_USR0, MEMORY_CONFIG_PFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,

  // External Serial Data Flash (M25P16 2MByte)
  /* S00: 64 Kbytes */  0x00800000, 0x0080FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S01: 64 Kbytes */  0x00810000, 0x0081FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S02: 64 Kbytes */  0x00820000, 0x0082FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S03: 64 Kbytes */  0x00830000, 0x0083FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S04: 64 Kbytes */  0x00840000, 0x0084FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S05: 64 Kbytes */  0x00850000, 0x0085FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S06: 64 Kbytes */  0x00860000, 0x0086FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S07: 64 Kbytes */  0x00870000, 0x0087FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S08: 64 Kbytes */  0x00880000, 0x0088FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S09: 64 Kbytes */  0x00890000, 0x0089FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S10: 64 Kbytes */  0x008A0000, 0x008AFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S11: 64 Kbytes */  0x008B0000, 0x008BFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S12: 64 Kbytes */  0x008C0000, 0x008CFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S13: 64 Kbytes */  0x008D0000, 0x008DFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S14: 64 Kbytes */  0x008E0000, 0x008EFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S15: 64 Kbytes */  0x008F0000, 0x008FFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S16: 64 Kbytes */  0x00900000, 0x0090FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S17: 64 Kbytes */  0x00910000, 0x0091FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S18: 64 Kbytes */  0x00920000, 0x0092FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S19: 64 Kbytes */  0x00930000, 0x0093FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S20: 64 Kbytes */  0x00940000, 0x0094FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S21: 64 Kbytes */  0x00950000, 0x0095FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S22: 64 Kbytes */  0x00960000, 0x0096FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S23: 64 Kbytes */  0x00970000, 0x0097FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S24: 64 Kbytes */  0x00980000, 0x0098FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S25: 64 Kbytes */  0x00990000, 0x0099FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S26: 64 Kbytes */  0x009A0000, 0x009AFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S27: 64 Kbytes */  0x009B0000, 0x009BFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S28: 64 Kbytes */  0x009C0000, 0x009CFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S29: 64 Kbytes */  0x009D0000, 0x009DFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S30: 64 Kbytes */  0x009E0000, 0x009EFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S31: 64 Kbytes */  0x009F0000, 0x009FFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
#ifdef _APP_XC
  /* S32: 64 KBytes */  0x00A00000, 0x00A0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S33: 64 KBytes */  0x00A10000, 0x00A1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S34: 64 KBytes */  0x00A20000, 0x00A2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S35: 64 KBytes */  0x00A30000, 0x00A3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S36: 64 KBytes */  0x00A40000, 0x00A4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S37: 64 KBytes */  0x00A50000, 0x00A5FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S38: 64 KBytes */  0x00A60000, 0x00A6FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S39: 64 KBytes */  0x00A70000, 0x00A7FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S40: 64 KBytes */  0x00A80000, 0x00A8FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S41: 64 KBytes */  0x00A90000, 0x00A9FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S42: 64 KBytes */  0x00AA0000, 0x00AAFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S43: 64 KBytes */  0x00AB0000, 0x00ABFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S44: 64 KBytes */  0x00AC0000, 0x00ACFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S45: 64 KBytes */  0x00AD0000, 0x00ADFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S46: 64 KBytes */  0x00AE0000, 0x00AEFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S47: 64 KBytes */  0x00AF0000, 0x00AFFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S48: 64 KBytes */  0x00B00000, 0x00B0FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S49: 64 KBytes */  0x00B10000, 0x00B1FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S50: 64 KBytes */  0x00B20000, 0x00B2FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S51: 64 KBytes */  0x00B30000, 0x00B3FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S52: 64 KBytes */  0x00B40000, 0x00B4FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S53: 64 KBytes */  0x00B50000, 0x00B5FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S54: 64 KBytes */  0x00B60000, 0x00B6FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S55: 64 KBytes */  0x00B70000, 0x00B7FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S56: 64 KBytes */  0x00B80000, 0x00B8FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S57: 64 KBytes */  0x00B90000, 0x00B9FFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S58: 64 KBytes */  0x00BA0000, 0x00BAFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S59: 64 KBytes */  0x00BB0000, 0x00BBFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S60: 64 KBytes */  0x00BC0000, 0x00BCFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S61: 64 KBytes */  0x00BD0000, 0x00BDFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S62: 64 KBytes */  0x00BE0000, 0x00BEFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
  /* S63: 64 KBytes */  0x00BF0000, 0x00BFFFFF, SECURITY_CRYPTO_KEY_NONE, MEMORY_CONFIG_SFLASH | MEMORY_CONFIG_READ | MEMORY_CONFIG_ERASE | MEMORY_CONFIG_WRITE,
#endif // _app_xc
#endif // _infineon_
};

#endif // _AXX_BOOTBLOCK

/////////////////////////////////////////////////////////////////////////////
//

MEMORYLAYOUT_DATA MEMORY_SECTOR_INFO MEMORYLAYOUT_QUAL * MemoryLayoutRetrieveSectorInfo( ULONG ulMemoryAddress )
{
  UWORD uwCount;

  // Search Memory Sector Info 
  for ( uwCount = 0; uwCount < sizeof( sMemorySectorInfos ) / sizeof( MEMORY_SECTOR_INFO ); uwCount++ ) 
    // Check Address Range
    if ( ulMemoryAddress >= sMemorySectorInfos[ uwCount ].ulLowerAddress && ulMemoryAddress <= sMemorySectorInfos[ uwCount ].ulUpperAddress ) 
      // Return if found
      return &sMemorySectorInfos[ uwCount ]; 

#ifdef _AXX_SYSAPP
  atomic_long_set_bits( &ulSystemWarnings, SYSTEMWARNINGS_ACCESSTOFORBIDDENAREA );
#endif

  // Requested Address not found
  return NULL;
}

/////////////////////////////////////////////////////////////////////////////
//

MEMORYLAYOUT_DATA MEMORY_SECTOR_INFO MEMORYLAYOUT_QUAL * MemoryLayoutRetrieveListInfo( ULONG * pulSize )
{
  *pulSize = sizeof( sMemorySectorInfos ) / sizeof( MEMORY_SECTOR_INFO );
  return sMemorySectorInfos;
}
