/****************************************************************************/ 
/* AUTO-GENERATED FILE - DO NOT MODIFY IT!                                  */ 
/****************************************************************************/ 
 
#define FPGA_HW_ANIOSTANDARD (2048ul) 
#define FPGA_HW_AUXENDOUT (262144ul) 
#define FPGA_HW_AUXIN (64ul) 
#define FPGA_HW_AUXOUT (128ul) 
#define FPGA_HW_BRIDGE1 (16ul) 
#define FPGA_HW_BRIDGE2 (16384ul) 
#define FPGA_HW_CURCHANMINMAX (1ul) 
#define FPGA_HW_ENCAUXBISS (8388608ul) 
#define FPGA_HW_ENCAUXENDAT (8ul) 
#define FPGA_HW_ENCHIPERFACE (32ul) 
#define FPGA_HW_ENCMAINBISS (4194304ul) 
#define FPGA_HW_ENCMAINENDAT (256ul) 
#define FPGA_HW_ENCMAINSINCOSABS (1024ul) 
#define FPGA_HW_ENCMAINSINCOSINC (512ul) 
#define FPGA_HW_ENCNIKON (65536ul) 
#define FPGA_HW_ENCTMGW (524288ul) 
#define FPGA_HW_ETHERCAT (2ul) 
#define FPGA_HW_ETHERCAT_DIRECTMII (8192ul) 
#define FPGA_HW_ETHERNET (2097152ul) 
#define FPGA_HW_ETHERPMC (32768ul) 
#define FPGA_HW_FASTINCRSIM (131072ul) 
#define FPGA_HW_PWMEX (1048576ul) 
#define FPGA_HW_VAUXSPL (4ul) 
#define FPGA_HW_VMAINSPL (4096ul) 
