/****************************************************************************/
/* AUTO-GENERATED FILE - DO NOT MODIFY IT!                                  */
/****************************************************************************/

// Inputs
#define FPGAIR_IFB_IU                  0
#define FPGAIR_IFB_IV                  1
#define FPGAIR_IFB_IW                  2
#define FPGAIR_IFB_AU                  3
#define FPGAIR_IFB_AV                  4
#define FPGAIR_IFB_AW                  5
#define FPGAIR_VDC_A                   6
#define FPGAIR_MINC_SIN                7
#define FPGAIR_MINC_COS                8
#define FPGAIR_IFB_BR2_AU              26
#define FPGAIR_IFB_BR2_AV              27
#define FPGAIR_IFB_BR2_AW              28
#define FPGAIR_IFB_BR1_AU              29
#define FPGAIR_IFB_BR1_AV              30
#define FPGAIR_IFB_BR1_AW              31
#define FPGAIR_IFB_BR2_IU              32
#define FPGAIR_IFB_BR2_IV              33
#define FPGAIR_IFB_BR2_IW              34
#define FPGAIR_IFB_BR1_IU              35
#define FPGAIR_IFB_BR1_IV              36
#define FPGAIR_IFB_BR1_IW              37
#define FPGAIR_IREF_FQ                 9
#define FPGAIR_K_SIN                   21
#define FPGAIR_K_COS                   22
#define FPGAIR_VDC_I                   10
#define FPGAIR_VAC_ARS                 11
#define FPGAIR_VAC_AST                 12
#define FPGAIR_VAC_IRS                 13
#define FPGAIR_VAC_IST                 14
#define FPGAIR_P_KI                    16
#define FPGAIR_P_KP                    17
#define FPGAIR_P_OUTSHIFT              18
#define FPGAIR_P_OUTLIM                19
#define FPGAIR_IREF_D                  20
#define FPGAIR_P_CORR_VD               23
#define FPGAIR_P_CORR_VQ               24
#define FPGAIR_P_VDC_SETVAL            25
#define FPGAIR_P_CORR_ID               38
#define FPGAIR_P_CORR_IQ               39
#define FPGAIR_P_SET_INTSTS            40
#define FPGAIR_P_INTSTS_D              41
#define FPGAIR_P_INTSTS_Q              42

// Registers
#define FPGAIR_VOUT_U                  0
#define FPGAIR_VOUT_V                  8
#define FPGAIR_VOUT_W                  16
#define FPGAIR_VDIF_UV                 24
#define FPGAIR_VDIF_UW                 32
#define FPGAIR_VDIF_VW                 40
#define FPGAIR_VSUM_UV                 48
#define FPGAIR_VSUM_UW                 56
#define FPGAIR_VSUM_VW                 64
#define FPGAIR_VDC_OUT                 72
#define FPGAIR_VDC_ARMC                184
#define FPGAIR_DONE                    504
#define FPGAIR_IFB_ID                  80
#define FPGAIR_IFB_AD                  88
#define FPGAIR_IFB_IQ                  96
#define FPGAIR_IFB_AQ                  104
#define FPGAIR_VOUT_D                  112
#define FPGAIR_VOUT_Q                  120
#define FPGAIR_C_ZERO                  128
#define FPGAIR_C_1DSQT3                136
#define FPGAIR_C_SQT3D2                144
#define FPGAIR_C_1D2                   152
#define FPGAIR_S_KI_D                  160
#define FPGAIR_S_KI_Q                  168
#define FPGAIR_C_1D3                   176
#define FPGAIR_T_SIND3                 192
#define FPGAIR_T_COSD3                 200
#define FPGAIR_T_SINDSQT3              208
#define FPGAIR_T_COSDSQT3              216
#define FPGAIR_C_1D125                 224
#define FPGAIR_T_VOUT_B                232
#define FPGAIR_T_LMTSHIFT              240
#define FPGAIR_T_LMTLIM                248
#define FPGAIR_P_VDC_SEL               256
#define FPGAIR_P_VDC_VAL               264
#define FPGAIR_T_IFBEQ_U               272
#define FPGAIR_T_IFBEQ_V               280
#define FPGAIR_T_IFBEQ_W               288
#define FPGAIR_C_1D4                   296
#define FPGAIR_C_1D8                   304
#define FPGAIR_C_7D8                   312
#define FPGAIR_T_VOUT_D                320
#define FPGAIR_T_VOUT_Q                328
#define FPGAIR_T_FLTIFB_ID             336
#define FPGAIR_T_FLTIFB_IQ             344
#define FPGAIR_T_INTSTS_D              352
#define FPGAIR_T_INTSTS_Q              360

// Outputs
#define FPGAIR_RGO_VOUT_U              68
#define FPGAIR_RGO_VOUT_V              69
#define FPGAIR_RGO_IFB_AD              64
#define FPGAIR_RGO_IFB_AQ              65
#define FPGAIR_RGO_VOUT_D              66
#define FPGAIR_RGO_VOUT_Q              67
